### ISSUE TITLE
The hyperlink doesn't lead to the APP but leads to your portfolio page......

### ISSUE THREAD

**Issue by BharZInstein** [ankushKun/animedoro-timer#17]
The Hyperlink "Here" Doesn't lead to the app 
<img width="829" alt="Screenshot 2022-05-09 132137" src="https://user-images.githubusercontent.com/81548305/167364850-1c9c9b02-b78e-4b77-b5dc-6e56018286ea.png">
whereas redirects to your portfolio page...

**Comment by ankushKun** [comment]
@BharZInstein Fixed the broken link 👍 
https://ankushkun.github.io/animedoro-timer/Animedoro/

closing the issue
