### ISSUE TITLE
Animedoro timer end glitch error

### ISSUE THREAD

**Issue by Code-Blender-7** [ankushKun/animedoro-timer#2]
Once the Animedoro timer ends, it would create a glitch text while instead of printing a single text. 

A video has been posted to get a clear view on the issue
https://user-images.githubusercontent.com/72243209/106360916-5121e080-6345-11eb-9786-dd1c3380a97c.mp4

**Comment by Moiz-I** [comment]
Same for me, including a never ending stream of notifications that kep soming even when I close the tab: 
![image](https://user-images.githubusercontent.com/69677514/118358953-fff6cf00-b578-11eb-8b3a-bef6c542f4dd.png)
