### ISSUE TITLE
contributing.md file missing

### ISSUE THREAD

**Issue by nileshlad09** [ankushKun/animedoro-timer#29]
According to hacktoberfest guidelines a contributing.md file should be there for projects which are participating in hacktoberfest.
Please assign this issue to me...

**Comment by nileshlad09** [comment]
Hey you can assign this to any one else

**Comment by TAMMY1942** [comment]
Hey plz assign this issue to me I can do this

**Comment by ankushKun** [comment]
This issue was resolved in a previous PR, coding it now
